name: ci

on:
  push:
    branches-ignore:
      - "master"
      - "develop"
  pull_request:

jobs:
  test:
    name: test
    strategy:
      matrix:
        node: [ 14, 16 ]
    runs-on: ubuntu-20.04
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Vienna"
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npx lerna run build
      - run: npm t -- --runInBand --ci --bail
